"""Perguntas fixas em PT-BR (gerais). Complementadas por matemática no seed até 150.

Cada item: quatro textos (option_a…option_d) e exatamente uma letra correta em
correct_choice ('A'–'D'), alinhada ao texto daquela alternativa.
"""

TRIVIA: list[dict[str, str]] = [
    {
        "prompt": "Qual é a capital do Brasil?",
        "option_a": "Brasília",
        "option_b": "Rio de Janeiro",
        "option_c": "São Paulo",
        "option_d": "Salvador",
        "correct_choice": "A",
        "category": "Geografia",
    },
    {
        "prompt": "Em que ano o Brasil foi descoberto por Pedro Álvares Cabral?",
        "option_a": "1498",
        "option_b": "1500",
        "option_c": "1502",
        "option_d": "1522",
        "correct_choice": "B",
        "category": "História",
    },
    {
        "prompt": "Quantos estados tem o Brasil (incluindo o DF)?",
        "option_a": "25",
        "option_b": "26",
        "option_c": "27",
        "option_d": "28",
        "correct_choice": "C",
        "category": "Geografia",
    },
    {
        "prompt": "Qual planeta é conhecido como Planeta Vermelho?",
        "option_a": "Vênus",
        "option_b": "Marte",
        "option_c": "Júpiter",
        "option_d": "Saturno",
        "correct_choice": "B",
        "category": "Ciência",
    },
    {
        "prompt": "Quem pintou a Mona Lisa?",
        "option_a": "Michelangelo",
        "option_b": "Leonardo da Vinci",
        "option_c": "Rafael",
        "option_d": "Van Gogh",
        "correct_choice": "B",
        "category": "Arte",
    },
    {
        "prompt": "Qual é o maior oceano da Terra?",
        "option_a": "Atlântico",
        "option_b": "Índico",
        "option_c": "Pacífico",
        "option_d": "Ártico",
        "correct_choice": "C",
        "category": "Geografia",
    },
    {
        "prompt": "Qual gás as plantas absorvem da atmosfera na fotossíntese?",
        "option_a": "Oxigênio",
        "option_b": "Nitrogênio",
        "option_c": "Dióxido de carbono",
        "option_d": "Hélio",
        "correct_choice": "C",
        "category": "Ciência",
    },
    {
        "prompt": "Qual é o menor país do mundo?",
        "option_a": "Mônaco",
        "option_b": "Vaticano",
        "option_c": "San Marino",
        "option_d": "Liechtenstein",
        "correct_choice": "B",
        "category": "Geografia",
    },
    {
        "prompt": "Quem escreveu 'Dom Casmurro'?",
        "option_a": "Machado de Assis",
        "option_b": "José de Alencar",
        "option_c": "Clarice Lispector",
        "option_d": "Jorge Amado",
        "correct_choice": "A",
        "category": "Literatura",
    },
    {
        "prompt": "Qual instrumento mede a temperatura?",
        "option_a": "Barômetro",
        "option_b": "Termômetro",
        "option_c": "Anemômetro",
        "option_d": "Higrômetro",
        "correct_choice": "B",
        "category": "Ciência",
    },
    {
        "prompt": "Qual é a fórmula da água?",
        "option_a": "CO2",
        "option_b": "H2O",
        "option_c": "O2",
        "option_d": "NaCl",
        "correct_choice": "B",
        "category": "Ciência",
    },
    {
        "prompt": "Em qual continente fica o Egito?",
        "option_a": "Ásia",
        "option_b": "Europa",
        "option_c": "África",
        "option_d": "Oceania",
        "correct_choice": "C",
        "category": "Geografia",
    },
    {
        "prompt": "Qual time brasileiro é conhecido como 'Timão'?",
        "option_a": "Flamengo",
        "option_b": "Palmeiras",
        "option_c": "Corinthians",
        "option_d": "São Paulo",
        "correct_choice": "C",
        "category": "Esportes",
    },
    {
        "prompt": "Quantos minutos tem uma partida de futebol (sem acréscimos)?",
        "option_a": "80",
        "option_b": "85",
        "option_c": "90",
        "option_d": "95",
        "correct_choice": "C",
        "category": "Esportes",
    },
    {
        "prompt": "Qual é a moeda oficial do Japão?",
        "option_a": "Won",
        "option_b": "Yuan",
        "option_c": "Iene",
        "option_d": "Ringgit",
        "correct_choice": "C",
        "category": "Cultura",
    },
    {
        "prompt": "Quem compôs a 'Nona Sinfonia' com o 'Hino à Alegria'?",
        "option_a": "Mozart",
        "option_b": "Beethoven",
        "option_c": "Bach",
        "option_d": "Chopin",
        "correct_choice": "B",
        "category": "Música",
    },
    {
        "prompt": "Qual é o maior mamífero do mundo?",
        "option_a": "Elefante africano",
        "option_b": "Baleia-azul",
        "option_c": "Girafa",
        "option_d": "Orca",
        "correct_choice": "B",
        "category": "Natureza",
    },
    {
        "prompt": "Qual elemento químico tem símbolo 'O'?",
        "option_a": "Ouro",
        "option_b": "Oxigênio",
        "option_c": "Ósmio",
        "option_d": "Ozônio",
        "correct_choice": "B",
        "category": "Ciência",
    },
    {
        "prompt": "Qual cidade brasileira é famosa pelo carnaval e pelo Cristo Redentor?",
        "option_a": "Salvador",
        "option_b": "Recife",
        "option_c": "Rio de Janeiro",
        "option_d": "Olinda",
        "correct_choice": "C",
        "category": "Cultura",
    },
    {
        "prompt": "Quem foi o primeiro homem a pisar na Lua?",
        "option_a": "Buzz Aldrin",
        "option_b": "Neil Armstrong",
        "option_c": "Yuri Gagarin",
        "option_d": "John Glenn",
        "correct_choice": "B",
        "category": "História",
    },
    {
        "prompt": "Qual país tem formato de bota na Europa?",
        "option_a": "Grécia",
        "option_b": "Itália",
        "option_c": "Espanha",
        "option_d": "Portugal",
        "correct_choice": "B",
        "category": "Geografia",
    },
    {
        "prompt": "Qual é a velocidade da luz (aproximada no vácuo)?",
        "option_a": "300 km/s",
        "option_b": "30.000 km/s",
        "option_c": "300.000 km/s",
        "option_d": "3.000.000 km/s",
        "correct_choice": "C",
        "category": "Ciência",
    },
    {
        "prompt": "Qual fruta é conhecida por conter potássio em abundância?",
        "option_a": "Maçã",
        "option_b": "Uva",
        "option_c": "Banana",
        "option_d": "Limão",
        "correct_choice": "C",
        "category": "Cultura",
    },
    {
        "prompt": "Qual oceano banha a costa leste do Brasil?",
        "option_a": "Pacífico",
        "option_b": "Índico",
        "option_c": "Atlântico",
        "option_d": "Ártico",
        "correct_choice": "C",
        "category": "Geografia",
    },
    {
        "prompt": "Qual é a língua oficial do Brasil?",
        "option_a": "Espanhol",
        "option_b": "Inglês",
        "option_c": "Português",
        "option_d": "Francês",
        "correct_choice": "C",
        "category": "Cultura",
    },
    {
        "prompt": "Quantos lados tem um triângulo?",
        "option_a": "2",
        "option_b": "3",
        "option_c": "4",
        "option_d": "5",
        "correct_choice": "B",
        "category": "Matemática",
    },
    {
        "prompt": "Qual destes é um réptil?",
        "option_a": "Baleia",
        "option_b": "Morcego",
        "option_c": "Jacaré",
        "option_d": "Pinguim",
        "correct_choice": "C",
        "category": "Natureza",
    },
    {
        "prompt": "Qual cidade é a capital de Portugal?",
        "option_a": "Porto",
        "option_b": "Lisboa",
        "option_c": "Coimbra",
        "option_d": "Braga",
        "correct_choice": "B",
        "category": "Geografia",
    },
    {
        "prompt": "Qual destes é um metal precioso?",
        "option_a": "Enxofre",
        "option_b": "Ferro",
        "option_c": "Ouro",
        "option_d": "Alumínio",
        "correct_choice": "C",
        "category": "Ciência",
    },
    {
        "prompt": "Quem pintou 'Guernica'?",
        "option_a": "Dalí",
        "option_b": "Picasso",
        "option_c": "Miró",
        "option_d": "Goya",
        "correct_choice": "B",
        "category": "Arte",
    },
    {
        "prompt": "Qual é o continente mais populoso?",
        "option_a": "África",
        "option_b": "Europa",
        "option_c": "Ásia",
        "option_d": "América",
        "correct_choice": "C",
        "category": "Geografia",
    },
    {
        "prompt": "Qual planeta é o maior do Sistema Solar?",
        "option_a": "Saturno",
        "option_b": "Júpiter",
        "option_c": "Netuno",
        "option_d": "Urano",
        "correct_choice": "B",
        "category": "Ciência",
    },
    {
        "prompt": "Qual é a unidade de medida de corrente elétrica no SI?",
        "option_a": "Volt",
        "option_b": "Ohm",
        "option_c": "Ampère",
        "option_d": "Watt",
        "correct_choice": "C",
        "category": "Ciência",
    },
    {
        "prompt": "Qual destes é um polígono de quatro lados?",
        "option_a": "Triângulo",
        "option_b": "Pentágono",
        "option_c": "Quadrado",
        "option_d": "Hexágono",
        "correct_choice": "C",
        "category": "Matemática",
    },
    {
        "prompt": "Quem escreveu 'O Pequeno Príncipe'?",
        "option_a": "Jules Verne",
        "option_b": "Antoine de Saint-Exupéry",
        "option_c": "Victor Hugo",
        "option_d": "Charles Dickens",
        "correct_choice": "B",
        "category": "Literatura",
    },
    {
        "prompt": "Qual é o maior deserto quente do mundo?",
        "option_a": "Gobi",
        "option_b": "Saara",
        "option_c": "Atacama",
        "option_d": "Arábico",
        "correct_choice": "B",
        "category": "Geografia",
    },
    {
        "prompt": "Qual gás compõe cerca de 78% do ar que respiramos?",
        "option_a": "Oxigênio",
        "option_b": "Dióxido de carbono",
        "option_c": "Nitrogênio",
        "option_d": "Hidrogênio",
        "correct_choice": "C",
        "category": "Ciência",
    },
    {
        "prompt": "Qual país sediou a Copa do Mundo FIFA de 2014?",
        "option_a": "Alemanha",
        "option_b": "África do Sul",
        "option_c": "Brasil",
        "option_d": "Rússia",
        "correct_choice": "C",
        "category": "Esportes",
    },
    {
        "prompt": "Qual é a montanha mais alta do mundo?",
        "option_a": "K2",
        "option_b": "Everest",
        "option_c": "Kilimanjaro",
        "option_d": "Aconcágua",
        "correct_choice": "B",
        "category": "Geografia",
    },
    {
        "prompt": "Qual destes é um mamífero?",
        "option_a": "Tubarão",
        "option_b": "Sapo",
        "option_c": "Baleia",
        "option_d": "Piranha",
        "correct_choice": "C",
        "category": "Natureza",
    },
    {
        "prompt": "Qual é a capital da Argentina?",
        "option_a": "Rosário",
        "option_b": "Córdoba",
        "option_c": "Buenos Aires",
        "option_d": "Mendoza",
        "correct_choice": "C",
        "category": "Geografia",
    },
    {
        "prompt": "Quantos segundos tem um minuto?",
        "option_a": "30",
        "option_b": "45",
        "option_c": "60",
        "option_d": "100",
        "correct_choice": "C",
        "category": "Matemática",
    },
    {
        "prompt": "Qual é o resultado de 12 × 5?",
        "option_a": "50",
        "option_b": "55",
        "option_c": "60",
        "option_d": "65",
        "correct_choice": "C",
        "category": "Matemática",
    },
    {
        "prompt": "Qual destes é um estado da região Nordeste do Brasil?",
        "option_a": "Paraná",
        "option_b": "Goiás",
        "option_c": "Bahia",
        "option_d": "Mato Grosso",
        "correct_choice": "C",
        "category": "Geografia",
    },
    {
        "prompt": "Quem desenvolveu a teoria da relatividade?",
        "option_a": "Isaac Newton",
        "option_b": "Albert Einstein",
        "option_c": "Galileu Galilei",
        "option_d": "Stephen Hawking",
        "correct_choice": "B",
        "category": "Ciência",
    },
    {
        "prompt": "Qual é a cor obtida misturando azul e amarelo?",
        "option_a": "Vermelho",
        "option_b": "Roxo",
        "option_c": "Verde",
        "option_d": "Laranja",
        "correct_choice": "C",
        "category": "Cultura",
    },
    {
        "prompt": "Qual é o menor planeta do Sistema Solar?",
        "option_a": "Mercúrio",
        "option_b": "Marte",
        "option_c": "Vênus",
        "option_d": "Plutão",
        "correct_choice": "A",
        "category": "Ciência",
    },
    {
        "prompt": "Qual organela produz energia (ATP) na célula?",
        "option_a": "Núcleo",
        "option_b": "Ribossomo",
        "option_c": "Mitocôndria",
        "option_d": "Lisossomo",
        "correct_choice": "C",
        "category": "Ciência",
    },
    {
        "prompt": "Qual é a capital do Canadá?",
        "option_a": "Toronto",
        "option_b": "Vancouver",
        "option_c": "Ottawa",
        "option_d": "Montreal",
        "correct_choice": "C",
        "category": "Geografia",
    },
    {
        "prompt": "Qual oceano é o segundo maior do mundo?",
        "option_a": "Índico",
        "option_b": "Atlântico",
        "option_c": "Pacífico",
        "option_d": "Ártico",
        "correct_choice": "B",
        "category": "Geografia",
    },
    {
        "prompt": "Qual destes é um gas nobre?",
        "option_a": "Cloro",
        "option_b": "Neônio",
        "option_c": "Flúor",
        "option_d": "Bromo",
        "correct_choice": "B",
        "category": "Ciência",
    },
    {
        "prompt": "Qual é a raiz quadrada de 81?",
        "option_a": "7",
        "option_b": "8",
        "option_c": "9",
        "option_d": "10",
        "correct_choice": "C",
        "category": "Matemática",
    },
    {
        "prompt": "Qual país é famoso pelas tulipas e moinhos de vento?",
        "option_a": "Bélgica",
        "option_b": "Holanda (Países Baixos)",
        "option_c": "Dinamarca",
        "option_d": "Suécia",
        "correct_choice": "B",
        "category": "Geografia",
    },
    {
        "prompt": "Qual é o maior animal terrestre?",
        "option_a": "Rinoceronte",
        "option_b": "Elefante-africano",
        "option_c": "Girafa",
        "option_d": "Hipopótamo",
        "correct_choice": "B",
        "category": "Natureza",
    },
    {
        "prompt": "Qual destes NÃO é um planeta do Sistema Solar (atual classificação)?",
        "option_a": "Marte",
        "option_b": "Vênus",
        "option_c": "Plutão",
        "option_d": "Urano",
        "correct_choice": "C",
        "category": "Ciência",
    },
    {
        "prompt": "Qual é a capital da França?",
        "option_a": "Lyon",
        "option_b": "Marselha",
        "option_c": "Paris",
        "option_d": "Nice",
        "correct_choice": "C",
        "category": "Geografia",
    },
    {
        "prompt": "Qual é o resultado de 144 ÷ 12?",
        "option_a": "10",
        "option_b": "11",
        "option_c": "12",
        "option_d": "13",
        "correct_choice": "C",
        "category": "Matemática",
    },
    {
        "prompt": "Qual compositor surdo ainda assim criou sinfonias memoráveis?",
        "option_a": "Mozart",
        "option_b": "Beethoven",
        "option_c": "Haydn",
        "option_d": "Schubert",
        "correct_choice": "B",
        "category": "Música",
    },
    {
        "prompt": "Qual é a fórmula do sal de cozinha (cloreto de sódio)?",
        "option_a": "H2O",
        "option_b": "CO2",
        "option_c": "NaCl",
        "option_d": "KCl",
        "correct_choice": "C",
        "category": "Ciência",
    },
    {
        "prompt": "Qual país tem formato alongado na América do Sul (costa no Pacífico)?",
        "option_a": "Peru",
        "option_b": "Chile",
        "option_c": "Equador",
        "option_d": "Colômbia",
        "correct_choice": "B",
        "category": "Geografia",
    },
    {
        "prompt": "Quantos lados tem um hexágono?",
        "option_a": "5",
        "option_b": "6",
        "option_c": "7",
        "option_d": "8",
        "correct_choice": "B",
        "category": "Matemática",
    },
    {
        "prompt": "Qual é a capital da Espanha?",
        "option_a": "Barcelona",
        "option_b": "Sevilha",
        "option_c": "Madri",
        "option_d": "Valência",
        "correct_choice": "C",
        "category": "Geografia",
    },
    {
        "prompt": "Qual destes é um satélite natural da Terra?",
        "option_a": "Fobos",
        "option_b": "Europa",
        "option_c": "Lua",
        "option_d": "Titã",
        "correct_choice": "C",
        "category": "Ciência",
    },
    {
        "prompt": "Qual esporte usa uma rede no meio da quadra e raquetes?",
        "option_a": "Basquete",
        "option_b": "Tênis",
        "option_c": "Handebol",
        "option_d": "Vôlei",
        "correct_choice": "B",
        "category": "Esportes",
    },
    {
        "prompt": "Qual é o valor de π (pi) aproximado comumente?",
        "option_a": "2,14",
        "option_b": "3,14",
        "option_c": "4,14",
        "option_d": "1,41",
        "correct_choice": "B",
        "category": "Matemática",
    },
    {
        "prompt": "Qual é a capital dos Estados Unidos?",
        "option_a": "Nova York",
        "option_b": "Los Angeles",
        "option_c": "Washington, D.C.",
        "option_d": "Chicago",
        "correct_choice": "C",
        "category": "Geografia",
    },
    {
        "prompt": "Qual destes é um mamífero voador?",
        "option_a": "Águia",
        "option_b": "Morcego",
        "option_c": "Pinguim",
        "option_d": "Coruja",
        "correct_choice": "B",
        "category": "Natureza",
    },
    {
        "prompt": "Qual é o resultado de 7³ (7 elevado a 3)?",
        "option_a": "343",
        "option_b": "243",
        "option_c": "294",
        "option_d": "210",
        "correct_choice": "A",
        "category": "Matemática",
    },
    {
        "prompt": "Qual oceano banha a costa oeste da América do Sul?",
        "option_a": "Atlântico",
        "option_b": "Índico",
        "option_c": "Pacífico",
        "option_d": "Ártico",
        "correct_choice": "C",
        "category": "Geografia",
    },
    {
        "prompt": "Qual é a capital da Itália?",
        "option_a": "Milão",
        "option_b": "Veneza",
        "option_c": "Roma",
        "option_d": "Nápoles",
        "correct_choice": "C",
        "category": "Geografia",
    },
    {
        "prompt": "Qual destes é um metal líquido à temperatura ambiente?",
        "option_a": "Sódio",
        "option_b": "Mercúrio",
        "option_c": "Chumbo",
        "option_d": "Zinco",
        "correct_choice": "B",
        "category": "Ciência",
    },
    {
        "prompt": "Qual é a capital da Alemanha?",
        "option_a": "Munique",
        "option_b": "Hamburgo",
        "option_c": "Berlim",
        "option_d": "Frankfurt",
        "correct_choice": "C",
        "category": "Geografia",
    },
    {
        "prompt": "Qual é o resultado de 15% de 200?",
        "option_a": "20",
        "option_b": "25",
        "option_c": "30",
        "option_d": "35",
        "correct_choice": "C",
        "category": "Matemática",
    },
    {
        "prompt": "Qual destes é um primata?",
        "option_a": "Urso",
        "option_b": "Lobo",
        "option_c": "Chimpanzé",
        "option_d": "Canguru",
        "correct_choice": "C",
        "category": "Natureza",
    },
    {
        "prompt": "Qual é a capital do Chile?",
        "option_a": "Valparaíso",
        "option_b": "Santiago",
        "option_c": "Concepción",
        "option_d": "Antofagasta",
        "correct_choice": "B",
        "category": "Geografia",
    },
    {
        "prompt": "Qual é o resultado de 2¹⁰ (2 elevado a 10)?",
        "option_a": "512",
        "option_b": "1024",
        "option_c": "2048",
        "option_d": "256",
        "correct_choice": "B",
        "category": "Matemática",
    },
    {
        "prompt": "Qual é a capital da Austrália?",
        "option_a": "Sydney",
        "option_b": "Melbourne",
        "option_c": "Canberra",
        "option_d": "Brisbane",
        "correct_choice": "C",
        "category": "Geografia",
    },
    {
        "prompt": "Qual destes é um instrumento de cordas?",
        "option_a": "Flauta",
        "option_b": "Trompete",
        "option_c": "Violão",
        "option_d": "Bateria",
        "correct_choice": "C",
        "category": "Música",
    },
    {
        "prompt": "Qual é a capital do México?",
        "option_a": "Guadalajara",
        "option_b": "Monterrey",
        "option_c": "Cidade do México",
        "option_d": "Cancún",
        "correct_choice": "C",
        "category": "Geografia",
    },
    {
        "prompt": "Qual é o resultado de 1000 ÷ 25?",
        "option_a": "25",
        "option_b": "40",
        "option_c": "50",
        "option_d": "20",
        "correct_choice": "B",
        "category": "Matemática",
    },
    {
        "prompt": "Qual é a capital do Peru?",
        "option_a": "Cusco",
        "option_b": "Arequipa",
        "option_c": "Lima",
        "option_d": "Trujillo",
        "correct_choice": "C",
        "category": "Geografia",
    },
    {
        "prompt": "Qual é o resultado de 9 × 8?",
        "option_a": "63",
        "option_b": "64",
        "option_c": "72",
        "option_d": "81",
        "correct_choice": "C",
        "category": "Matemática",
    },
    {
        "prompt": "Qual é a capital da Rússia?",
        "option_a": "São Petersburgo",
        "option_b": "Moscou",
        "option_c": "Kazan",
        "option_d": "Novosibirsk",
        "correct_choice": "B",
        "category": "Geografia",
    },
    {
        "prompt": "Qual é o resultado de 50 − 17?",
        "option_a": "31",
        "option_b": "32",
        "option_c": "33",
        "option_d": "34",
        "correct_choice": "C",
        "category": "Matemática",
    },
    {
        "prompt": "Qual é a capital da China?",
        "option_a": "Xangai",
        "option_b": "Hong Kong",
        "option_c": "Pequim (Beijing)",
        "option_d": "Cantão",
        "correct_choice": "C",
        "category": "Geografia",
    },
    {
        "prompt": "Qual é o resultado de 3! (fatorial de 3)?",
        "option_a": "3",
        "option_b": "6",
        "option_c": "9",
        "option_d": "12",
        "correct_choice": "B",
        "category": "Matemática",
    },
    {
        "prompt": "Qual é a capital do Egito?",
        "option_a": "Alexandria",
        "option_b": "Gizé",
        "option_c": "Cairo",
        "option_d": "Luxor",
        "correct_choice": "C",
        "category": "Geografia",
    },
    {
        "prompt": "Qual é o resultado de 11 × 11?",
        "option_a": "111",
        "option_b": "121",
        "option_c": "131",
        "option_d": "101",
        "correct_choice": "B",
        "category": "Matemática",
    },
    {
        "prompt": "Qual é a capital da Índia?",
        "option_a": "Mumbai",
        "option_b": "Nova Deli",
        "option_c": "Calcutá",
        "option_d": "Bangalore",
        "correct_choice": "B",
        "category": "Geografia",
    },
    {
        "prompt": "Qual é o resultado de 360 ÷ 12?",
        "option_a": "20",
        "option_b": "25",
        "option_c": "30",
        "option_d": "35",
        "correct_choice": "C",
        "category": "Matemática",
    },
    {
        "prompt": "Qual é a capital do Reino Unido?",
        "option_a": "Manchester",
        "option_b": "Liverpool",
        "option_c": "Londres",
        "option_d": "Edimburgo",
        "correct_choice": "C",
        "category": "Geografia",
    },
    {
        "prompt": "Qual é o resultado de 0,5 + 0,25?",
        "option_a": "0,5",
        "option_b": "0,65",
        "option_c": "0,75",
        "option_d": "1",
        "correct_choice": "C",
        "category": "Matemática",
    },
    {
        "prompt": "Qual é a capital do Japão?",
        "option_a": "Osaka",
        "option_b": "Quioto",
        "option_c": "Tóquio",
        "option_d": "Yokohama",
        "correct_choice": "C",
        "category": "Geografia",
    },
    {
        "prompt": "Qual é o resultado de 5² + 12² (teorema de Pitágoras clássico)?",
        "option_a": "144",
        "option_b": "169",
        "option_c": "196",
        "option_d": "225",
        "correct_choice": "B",
        "category": "Matemática",
    },
    {
        "prompt": "Qual é a capital da Noruega?",
        "option_a": "Bergen",
        "option_b": "Trondheim",
        "option_c": "Oslo",
        "option_d": "Stavanger",
        "correct_choice": "C",
        "category": "Geografia",
    },
    {
        "prompt": "Qual é o resultado de 1 + 2 + 3 + 4 + 5?",
        "option_a": "10",
        "option_b": "12",
        "option_c": "15",
        "option_d": "20",
        "correct_choice": "C",
        "category": "Matemática",
    },
    {
        "prompt": "Qual é a capital da Suécia?",
        "option_a": "Gotemburgo",
        "option_b": "Malmö",
        "option_c": "Estocolmo",
        "option_d": "Uppsala",
        "correct_choice": "C",
        "category": "Geografia",
    },
    {
        "prompt": "Qual é o resultado de 45 ÷ 9?",
        "option_a": "4",
        "option_b": "5",
        "option_c": "6",
        "option_d": "7",
        "correct_choice": "B",
        "category": "Matemática",
    },
    {
        "prompt": "Qual é a capital da Grécia?",
        "option_a": "Salonica",
        "option_b": "Patras",
        "option_c": "Atenas",
        "option_d": "Heraclião",
        "correct_choice": "C",
        "category": "Geografia",
    },
    {
        "prompt": "Qual é o resultado de 20% de 250?",
        "option_a": "25",
        "option_b": "40",
        "option_c": "50",
        "option_d": "75",
        "correct_choice": "C",
        "category": "Matemática",
    },
    {
        "prompt": "Qual é a capital da Turquia?",
        "option_a": "Istambul",
        "option_b": "Izmir",
        "option_c": "Ancara",
        "option_d": "Antália",
        "correct_choice": "C",
        "category": "Geografia",
    },
    {
        "prompt": "Qual é o resultado de 2 + 2 × 3 (sem parênteses extras)?",
        "option_a": "12",
        "option_b": "10",
        "option_c": "8",
        "option_d": "9",
        "correct_choice": "C",
        "category": "Matemática",
    },
    {
        "prompt": "Qual é a capital da Coreia do Sul?",
        "option_a": "Busan",
        "option_b": "Incheon",
        "option_c": "Seul",
        "option_d": "Daegu",
        "correct_choice": "C",
        "category": "Geografia",
    },
    {
        "prompt": "Qual é o resultado de 13 + 27?",
        "option_a": "35",
        "option_b": "40",
        "option_c": "41",
        "option_d": "50",
        "correct_choice": "B",
        "category": "Matemática",
    },
    {
        "prompt": "Qual é a capital da Polônia?",
        "option_a": "Cracóvia",
        "option_b": "Gdansk",
        "option_c": "Varsóvia",
        "option_d": "Wroclaw",
        "correct_choice": "C",
        "category": "Geografia",
    },
    {
        "prompt": "Qual é o resultado de 6 × 7?",
        "option_a": "40",
        "option_b": "42",
        "option_c": "44",
        "option_d": "48",
        "correct_choice": "B",
        "category": "Matemática",
    },
    {
        "prompt": "Qual é a capital da África do Sul? (uma das capitais administrativas)",
        "option_a": "Joanesburgo",
        "option_b": "Durban",
        "option_c": "Pretória",
        "option_d": "Cidade do Cabo",
        "correct_choice": "C",
        "category": "Geografia",
    },
    {
        "prompt": "Qual é o resultado de 1 ÷ 0,25?",
        "option_a": "2",
        "option_b": "3",
        "option_c": "4",
        "option_d": "5",
        "correct_choice": "C",
        "category": "Matemática",
    },
    {
        "prompt": "Qual é a capital da Colômbia?",
        "option_a": "Medellín",
        "option_b": "Cali",
        "option_c": "Bogotá",
        "option_d": "Cartagena",
        "correct_choice": "C",
        "category": "Geografia",
    },
    {
        "prompt": "Qual é o resultado de 8²?",
        "option_a": "56",
        "option_b": "64",
        "option_c": "72",
        "option_d": "81",
        "correct_choice": "B",
        "category": "Matemática",
    },
]
