"""Gerado por import_docx_questions.py — não editar à mão se for reimportar."""

TRIVIA_IMPORT: list[dict[str, str]] = [
    {
        "prompt": 'Qual foi o ano em que o primeiro episódio foi lançado e qual é o nome dele?',
        "option_a": 'Passando um Trote (2007)',
        "option_b": 'Primeiro Dia (2010)',
        "option_c": 'Queijo Quente de Luxo (2010)',
        "option_d": 'A Força (2009)',
        "correct_choice": 'D',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual desses personagens é um Deus na série?',
        "option_a": 'Pairulito',
        "option_b": 'Saltitão',
        "option_c": 'Benson',
        "option_d": 'Musculoso',
        "correct_choice": 'A',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Na batalha final, um dos personagem morre para salvar todo o universo, qual é esse personagem?',
        "option_a": 'Pairulito',
        "option_b": 'Saltitão',
        "option_c": 'Fantasmão',
        "option_d": 'Eileen',
        "correct_choice": 'A',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Complete a frase “Eureca, Eureca...”',
        "option_a": 'Prove o macarrão e depois tire uma soneca',
        "option_b": 'Quebre sua cama e depois coma uma bisteca',
        "option_c": 'Mordecai e Rigby compraram uma cueca',
        "option_d": 'Jogue video game depois quebre uma caneca',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Quantos anos tem o Mordecai e o Rigby',
        "option_a": '20 anos',
        "option_b": '23 anos',
        "option_c": '19 anos',
        "option_d": '15 anos',
        "correct_choice": 'B',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual foi a pontuação de Mordecai e Rigby nos ossos quebrados contra (CGB)?',
        "option_a": '1.000.000 pontos',
        "option_b": '2.000.000 pontos',
        "option_c": '2.300.000 pontos',
        "option_d": '1.300.000 pontos',
        "correct_choice": 'D',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Onde a Margaret trabalha?',
        "option_a": 'Em uma loja de discos',
        "option_b": 'Em uma locadora',
        "option_c": 'No parque',
        "option_d": 'Em uma cafeteria',
        "correct_choice": 'D',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual o nome da namorada do Musculoso?',
        "option_a": 'Eileen',
        "option_b": 'Margaret',
        "option_c": 'CJ',
        "option_d": 'Starla',
        "correct_choice": 'D',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual o nome do irmão do Rigby',
        "option_a": 'Jorel',
        "option_b": 'Tom',
        "option_c": 'Don',
        "option_d": 'Maellard',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Quem é o dono do parque?',
        "option_a": 'Benson',
        "option_b": 'Pairulito',
        "option_c": 'Sr. Maellard',
        "option_d": 'Saltitão',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Quando o Mordecai e o Rigby se conheceram?',
        "option_a": 'No jardim de infância',
        "option_b": 'Na escola',
        "option_c": 'Na Faculdade',
        "option_d": 'No parque',
        "correct_choice": 'A',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual o nome do spin off de Apenas um Show transmitido no Brasil e América Latina?',
        "option_a": 'Outra Semana no Cartoon',
        "option_b": 'Toontubers',
        "option_c": 'CN Anything',
        "option_d": 'Apenas um Spin Off',
        "correct_choice": 'B',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual a verdadeira identidade do Thomas?',
        "option_a": 'Faz tudo',
        "option_b": 'Gerente de um parque concorrente',
        "option_c": 'Estagiário',
        "option_d": 'Espião',
        "correct_choice": 'D',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual o nome oficial do parque em Apenas um Show?',
        "option_a": 'Jellystone',
        "option_b": 'Parque Municipal de Elmore',
        "option_c": 'Não tem nome oficial',
        "option_d": 'East Pines',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual o verdadeiro nome do Musculoso?',
        "option_a": 'Mitch',
        "option_b": 'Michael',
        "option_c": 'Montgomery',
        "option_d": 'Marcos',
        "correct_choice": 'A',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Musculoso já foi campeão de um campeonato de…',
        "option_a": 'Tênis',
        "option_b": 'Bodybuilding',
        "option_c": 'Tiro ao alvo',
        "option_d": 'Basquete',
        "correct_choice": 'B',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Responda como o Musculoso: Sabe quem mais gosta de responder perguntas?',
        "option_a": 'Eu mesmo!',
        "option_b": 'O meu pai',
        "option_c": 'A minha mãe',
        "option_d": 'O Mordecai',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual o pet que o Benson adota e deixa sob os cuidados de Mordecai e Rigby em um episódio da sétima temporada?',
        "option_a": 'Sr. Bigodes Gato',
        "option_b": 'Tortuguita - Tartaruga',
        "option_c": 'Maçãzinha - Porco',
        "option_d": 'Quack Quack - Pato',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual o nome do criador de Apenas um Show?',
        "option_a": 'Genndy Tartakovsky',
        "option_b": 'Ted Turner',
        "option_c": 'Ian Jones-Quartey',
        "option_d": 'JG Quintel',
        "correct_choice": 'D',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual o jeito certo de comer um Sanduíche Mortal?',
        "option_a": 'Usando mullets e shorts jeans',
        "option_b": 'Deitado com os pés atrás da cabeça',
        "option_c": 'Com os pés enquanto assiste a uma fita VHS',
        "option_d": 'Você não come',
        "correct_choice": 'A',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual o nome do filme que faz o Rigby ter pesadelos?',
        "option_a": 'Olá, senhor',
        "option_b": 'Guerra dos Mundos',
        "option_c": 'Homem Galinha Gato 7 - A Vingança',
        "option_d": 'O Retorno do Boca Murcha',
        "correct_choice": 'A',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual o episódio em que todos os inimigos do Mordecai e o Rigby voltam para se vingar?',
        "option_a": 'Uma Batalha Final Épica de Verdade',
        "option_b": 'Guerra dos Formatos 2',
        "option_c": 'O Botão',
        "option_d": 'Saída 9B',
        "correct_choice": 'D',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Pra onde o Mordecai vai depois da CJ terminar com ele?',
        "option_a": 'Seatle',
        "option_b": 'Tocolândia',
        "option_c": 'Legendários',
        "option_d": 'Um programa de namoro.',
        "correct_choice": 'B',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Quantas temporadas tem Apenas um Show?',
        "option_a": '6',
        "option_b": '6',
        "option_c": '8',
        "option_d": '9',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Quem faz a voz do Mordecai na versão original?',
        "option_a": 'O criador da série',
        "option_b": 'Um dos storyboarders do show',
        "option_c": 'Um ex-segurança do Cartoon Network',
        "option_d": 'O irmão do ator que faz o Rigby',
        "correct_choice": 'A',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Com quem o Mordecai se casa no final da série?',
        "option_a": 'Margaret',
        "option_b": 'Stef',
        "option_c": 'Eileen',
        "option_d": 'CJ',
        "correct_choice": 'B',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Quem dubla o Mordecai e o Rigby no Brasil?',
        "option_a": 'Guilherme Briggs e Marco Ribeiro',
        "option_b": 'Sérgio Stern e Charles Emmanuel',
        "option_c": 'Sérgio Stern e Manolo Rey',
        "option_d": 'Charles Emmanuel e Marco Ribeiro',
        "correct_choice": 'B',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Por que o Saltitão é imortal?',
        "option_a": 'Ele nasceu assim',
        "option_b": 'Ele comeu um bolinho que lhe deu o poder da imortalidade',
        "option_c": 'Para lutar contra um bebê mágico do espaço',
        "option_d": 'Foi condenado a trabalhar para sempre no parque',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual o nome do gerente do outro parque e rival do Benson?',
        "option_a": 'Gene',
        "option_b": 'Sr. Maellard',
        "option_c": 'Klorgbane',
        "option_d": 'CBG',
        "correct_choice": 'A',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Como que o Rigby envia o Saltitão para o espaço sem querer?',
        "option_a": 'Fazendo um desejo errado para um gênio',
        "option_b": 'Inscrevendo ele para ser astronauta para fazer uma pegadinha',
        "option_c": 'Tocando um teclado mágico',
        "option_d": 'Com um estilingue gigante',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual pássaro é o Mordecai?',
        "option_a": 'Papagaio',
        "option_b": 'Gavião',
        "option_c": 'Arara Azul',
        "option_d": 'Gaio Azul',
        "correct_choice": 'D',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual o nome da banda do Mordecai e o Rigby?',
        "option_a": 'Os Mordecais e os Rigbys',
        "option_b": 'Soco no Ar',
        "option_c": 'A Força',
        "option_d": 'Ovocelente',
        "correct_choice": 'D',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual o nome do primo do Saltitão?',
        "option_a": 'Arnaldo',
        "option_b": 'César',
        "option_c": 'Zoa',
        "option_d": 'Yeti',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual a comida que faz o Rigby entrar em coma?',
        "option_a": 'Sanduíche Mortal',
        "option_b": 'Queijo Quente Duplo de Luxo',
        "option_c": 'Ovocelente',
        "option_d": 'Ultiburguer',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Quem é o melhor amigo do Musculoso?',
        "option_a": 'Fantasmão',
        "option_b": 'Mordecai',
        "option_c": 'Rigby',
        "option_d": 'Saltitão',
        "correct_choice": 'A',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Quem é a melhor amiga da Margaret?',
        "option_a": 'CJ',
        "option_b": 'Starla',
        "option_c": 'Eileen',
        "option_d": 'Cláudia',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'A qual comida o Rigby é alérgico?',
        "option_a": 'Arroz',
        "option_b": 'Macarrão',
        "option_c": 'Salsicha',
        "option_d": 'Ovo',
        "correct_choice": 'D',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual a profissão do irmão do Fantasmão?',
        "option_a": 'Bombeiro',
        "option_b": 'Encanador',
        "option_c": 'Policial',
        "option_d": 'Empresário',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Quantos filmes de Apenas um Show existem?',
        "option_a": '0',
        "option_b": '1',
        "option_c": '2',
        "option_d": '3',
        "correct_choice": 'B',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Por que o corpo do Rigby abandona ele no episódio O Corpo de Rigby',
        "option_a": 'Porque ele está fedendo',
        "option_b": 'Porque ele caiu do telhado',
        "option_c": 'Porque ele se alimenta mal',
        "option_d": 'Porque ele é feio',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Quem atirou no Rigby do futuro?',
        "option_a": 'Eileen',
        "option_b": 'Benson',
        "option_c": 'Mordecai do futuro',
        "option_d": 'Mordecai do presente',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Quem trabalha no parque?',
        "option_a": 'Benson, Mordecai, Rigby, Fantasmão, Musculoso, Pairulito e Saltitão.',
        "option_b": 'Benson, Margaret, Rigby, Eileen, Pairulito, Thomas, Fantasmão, CJ.',
        "option_c": 'Benson, Mordecai, ,Saltitão, Rigby, CJ, Margaret, Fantasmão, Pairulito e Musculoso.',
        "option_d": 'Benson, Fantasmão, Mordecai, ,Saltitão, CJ, Margaret, Cabeção e Rigby',
        "correct_choice": 'A',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual o nome do funcionário que o Rigby contrata para fazer o seu trabalho?',
        "option_a": 'Doug',
        "option_b": 'Domini',
        "option_c": 'Thomas',
        "option_d": 'Don',
        "correct_choice": 'A',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Complete “Haha, um toque pro seu…”',
        "option_a": 'Amigão',
        "option_b": 'Celular',
        "option_c": 'Futuro',
        "option_d": 'Chefe',
        "correct_choice": 'B',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Por que Mordecai e a Margaret terminam?',
        "option_a": 'Porque ela está apaixonado por outro',
        "option_b": 'Porque ela é muito mais velha que ele',
        "option_c": 'Porque ela vai se mudar',
        "option_d": 'Porque ela queria se casar e ele não',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'De quem é a criança que Mordecai e o Rigby precisam cuidar para salvar a vida do Musculoso?',
        "option_a": 'Morte',
        "option_b": 'Benson',
        "option_c": 'Klorgbane',
        "option_d": 'Anti-Pairulito',
        "correct_choice": 'A',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual a frase típica do Benson?',
        "option_a": 'Que belo show',
        "option_b": 'Voltem ao trabalho ou estão demitidos',
        "option_c": 'Cala boca',
        "option_d": 'Ooooohhhhh',
        "correct_choice": 'B',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Quem detém e quem detinha o recorde no jogo Ossos Quebrados?',
        "option_a": 'Saltitão e a Morte',
        "option_b": 'Mordecai e Klorgbane',
        "option_c": 'Musculoso e Fantasmão',
        "option_d": 'Mordecai/Rigby e Carlos Gomes Barbosa',
        "correct_choice": 'D',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual o nome da namorada do Fantasmão?',
        "option_a": 'Célia',
        "option_b": 'CJ',
        "option_c": 'Mona',
        "option_d": 'Starla',
        "correct_choice": 'A',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual o antigo nome do Saltitão?',
        "option_a": 'Andor',
        "option_b": 'Antonio',
        "option_c": 'Ando',
        "option_d": 'Antoane',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual o personagem que é uma nuvem?',
        "option_a": 'Pairulito',
        "option_b": 'Margaret',
        "option_c": 'CJ',
        "option_d": 'Starla',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'O que acontece com o parque na oitava temporada?',
        "option_a": 'Explode',
        "option_b": 'Vai para o espaço',
        "option_c": 'Encolhe',
        "option_d": 'É fechado',
        "correct_choice": 'B',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Por que o Mordecai precisa apagar as memórias dele com uma fita VHS?',
        "option_a": 'Porque ele não consegue esquecer a Margaret após terem terminado',
        "option_b": 'Porque ele viu o Pairulito pelado e não consegue tirar a imagem da cabeça',
        "option_c": 'Porque ele viu ele mesmo no futuro e precisa esquecer para não alterar a linha do tempo',
        "option_d": 'Porque ia ser engraçado',
        "correct_choice": 'B',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual o nome da música chiclete que possui o Rigby?',
        "option_a": 'Party Tonight',
        "option_b": 'Eureca, Eureca',
        "option_c": 'Olá, senhor',
        "option_d": 'O Verão Chegou',
        "correct_choice": 'D',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual o nome da competição de video games com personagens de Apenas um Show que aconteceu no Brasil em 2019?',
        "option_a": 'Toontubers Challenge',
        "option_b": 'Olimpíadas Toontubers',
        "option_c": 'Video Game Wizards',
        "option_d": 'Toontubers League',
        "correct_choice": 'D',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Em quem o Mordecai e o Rigby passam trotes no episódio Passando um Trote?',
        "option_a": 'Mestre dos Trotes',
        "option_b": 'Klorgbane',
        "option_c": 'Morte',
        "option_d": 'CGB',
        "correct_choice": 'A',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'O que está escrito no boné que o Rigby ganha ao comer uma omelete de 12 ovos em um restaurante?',
        "option_a": 'Eu sou Ovocelente',
        "option_b": 'Venci o Desafio do Ovo',
        "option_c": 'Cavaleiro da Távola Oval',
        "option_d": 'OVenci',
        "correct_choice": 'A',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual o instrumento que o Benson toca?',
        "option_a": 'Guitarra',
        "option_b": 'Violino',
        "option_c": 'Bateria',
        "option_d": 'Acordeon',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Rigby é um…',
        "option_a": 'Guaxinim',
        "option_b": 'Castor',
        "option_c": 'Garo',
        "option_d": 'Cachorro',
        "correct_choice": 'A',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Por que o Saltitão saltita?',
        "option_a": 'Não aprendeu a andar',
        "option_b": 'Tem problemas na perna por conta de uma aventura',
        "option_c": 'Por causa de uma promessa para a ex-namorada',
        "option_d": 'Para emagrecer',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual o nome da banda que Mordecai e o Rigby querem ver no episódio Ingressos para um Show Cafeinado?',
        "option_a": 'Metallica',
        "option_b": 'Mega Mortal pra Trás',
        "option_c": 'Death Kwon Doh',
        "option_d": 'Soco no Ar',
        "correct_choice": 'D',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'O Musculoso é um…',
        "option_a": 'Anão',
        "option_b": 'Duende',
        "option_c": 'Humano',
        "option_d": 'Alien',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Após perder uma aposta, o Mordecai precisa pintar o cabelo dele de que cor?',
        "option_a": 'Ruivo',
        "option_b": 'Moreno',
        "option_c": 'Loiro',
        "option_d": 'Branco',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual famoso dubla o Saltitão na versão original (EUA)?',
        "option_a": 'Mark Hamill',
        "option_b": 'Mel Gibson',
        "option_c": 'Adam Sandler',
        "option_d": 'Ed Murphy',
        "correct_choice": 'A',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual rapper famoso já apareceu em Apenas um Show?',
        "option_a": '50 Cent',
        "option_b": 'Tyler the Creator',
        "option_c": 'Eminem',
        "option_d": 'Drake',
        "correct_choice": 'B',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual música famosa de David Bowie toca no final de Apenas um Show?',
        "option_a": 'Starman',
        "option_b": 'Heroes',
        "option_c": 'Rebel Rebel',
        "option_d": 'Life on Mars',
        "correct_choice": 'B',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual funcionário do parque já ficou 1 ano inteiro sem tirar um dia de folga?',
        "option_a": 'Musculoso',
        "option_b": 'Fantasmão',
        "option_c": 'Pairulito',
        "option_d": 'Saltitão',
        "correct_choice": 'D',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual desses personagens é filho do dono do parque?',
        "option_a": 'Musculoso',
        "option_b": 'Fantasmão',
        "option_c": 'Pairulito',
        "option_d": 'Saltitão',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual instrumento o Musculoso sabe tocar?',
        "option_a": 'Trompete',
        "option_b": 'Guitarra',
        "option_c": 'Flauta',
        "option_d": 'Vuvuzela',
        "correct_choice": 'A',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual o nome dos especiais de Halloween  de Apenas um Show?',
        "option_a": 'Parque Aterrorizante',
        "option_b": 'Noites do Terror do Parque',
        "option_c": 'Contos de Terror do Parque',
        "option_d": 'Halloween no Parque',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual o nome que o Rigby adota e depois se arrepende?',
        "option_a": 'Metade Maravilha',
        "option_b": 'Canoa Furada',
        "option_c": 'CGB',
        "option_d": 'O Martelo',
        "correct_choice": 'B',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'O que é o Benson?',
        "option_a": 'um humano esquisito',
        "option_b": 'uma máquina de chicletes',
        "option_c": 'um alienígena',
        "option_d": 'um video game',
        "correct_choice": 'B',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual o nome do teclado mágico que o Rigby e o Mordecai no primeiro episódio da série?',
        "option_a": 'Piano Pianisson',
        "option_b": 'Ray Charles',
        "option_c": 'A Força',
        "option_d": 'Não tem nome',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Para onde o Rigby acidentalmente manda o Saltitão com o teclado mágico no primeiro episódio?',
        "option_a": 'para a lua',
        "option_b": 'para casa',
        "option_c": 'para o Everest',
        "option_d": 'para onde vivem os monstros',
        "correct_choice": 'A',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'O que acontece com Mordecai e o Rigby quando o Benson pede para eles comprarem um Queijo Quente de Luxo?',
        "option_a": 'eles lutam contra salsichas canibais',
        "option_b": 'eles aprendem a fazer manobras radicais com motocross',
        "option_c": 'eles viram astronautas',
        "option_d": 'eles voltam pra 1980',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'De que cor ficam as bolas de chiclete do Benson quando ele fica bravo?',
        "option_a": 'Azul',
        "option_b": 'Preto',
        "option_c": 'Vermelho',
        "option_d": 'Amarelo',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'O que o Monstro de Neve solta pela boca no episódio Dia da Apreciação?',
        "option_a": 'Fogo',
        "option_b": 'Gelo',
        "option_c": 'Raio',
        "option_d": 'Vento',
        "correct_choice": 'A',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'O que o Saltitão faz todo ano para manter sua imortalidade?',
        "option_a": 'uma dança',
        "option_b": 'um vídeo viral',
        "option_c": 'come asinhas de frango com molho picante',
        "option_d": 'assiste ao filme Jantar com Zumbis',
        "correct_choice": 'A',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual o nome da ex-namorada do Saltitão?',
        "option_a": 'Starla',
        "option_b": 'Margaret',
        "option_c": 'Eileen',
        "option_d": 'Mona',
        "correct_choice": 'D',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'O que o Pairulito usa como dinheiro?',
        "option_a": 'Papel picado',
        "option_b": 'Salsichas',
        "option_c": 'Pirulitos',
        "option_d": 'Chiclete',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'O que o Rigby confessa para a Margaret sobre a Eileen?',
        "option_a": 'que ele é apaixonado por ela',
        "option_b": 'que ela é irritante',
        "option_c": 'que ela é chata',
        "option_d": 'que ela fica bonita sem óculos.',
        "correct_choice": 'D',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'O que o Pairulito ordena o Benson fazer no episódio Pense Positivo?',
        "option_a": 'pare de gritar com o Mordecai e o Rigby',
        "option_b": 'abrace Mordecai e Rigby',
        "option_c": 'pague Mordecai e Rigby',
        "option_d": 'dance com Mordecai e Rigby',
        "correct_choice": 'A',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Onde o Musculoso e Fantasmão se conheceram?',
        "option_a": 'jardim de infância',
        "option_b": 'ensino médio',
        "option_c": 'faculdade',
        "option_d": 'no parque',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'No episódio Bolo de Graça é o aniversário de que personagem?',
        "option_a": 'Musculoso',
        "option_b": 'Saltitão',
        "option_c": 'Benson',
        "option_d": 'Pairulito',
        "correct_choice": 'B',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual desses personagens tem um problema com calvície?',
        "option_a": 'Fantasmão',
        "option_b": 'Saltitão',
        "option_c": 'Musculoso',
        "option_d": 'Mordecai',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual o sobrenome do Benson?',
        "option_a": 'Sorenstein',
        "option_b": 'Dunwoody',
        "option_c": 'Quintel',
        "option_d": 'Maellard',
        "correct_choice": 'B',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'O que todos os funcionários do parque tem que o Rigby não tem?',
        "option_a": 'uma casa',
        "option_b": 'um relógio do Carter e Briggs',
        "option_c": 'uma TV de tela plana',
        "option_d": 'um diploma do colegial',
        "correct_choice": 'D',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual o apelido que o Rigby recebeu após fazer uma cirurgia na nádega esquerda?',
        "option_a": 'Meio a Meio',
        "option_b": 'Metade Maravilha',
        "option_c": 'Tô Doido',
        "option_d": 'Canoa Furada',
        "correct_choice": 'B',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual golpe o Rigby aprende para ganhar do Mordecai nas brincadeiras de lutinha?',
        "option_a": 'Super Chute',
        "option_b": 'Soco Mortal',
        "option_c": 'Barrigada Sônica',
        "option_d": 'Tapão Cósmico',
        "correct_choice": 'B',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'O que tem na lua?',
        "option_a": 'Abraham Lincoln',
        "option_b": 'Queijo Minas',
        "option_c": 'Uma espécie de quimera',
        "option_d": 'A minha mãe',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual o maior medo do Rigby?',
        "option_a": 'a Morte',
        "option_b": 'o cheiro do sovaco do Musculoso',
        "option_c": 'Hamboning',
        "option_d": 'mascotes de parques temáticos',
        "correct_choice": 'D',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'O que acontece com o Pairulito quando Mordecai e Rigby tentam fazer um vídeo viral?',
        "option_a": 'ele é enviado para outra dimensão',
        "option_b": 'ele é enviado para a lua',
        "option_c": 'ele aprende a voar',
        "option_d": 'ele bate a cabeça  e esquece quem é',
        "correct_choice": 'A',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Quais bichos ficam apegados a Mordecai e Rigby e começam a imitá-los?',
        "option_a": 'Gansos',
        "option_b": 'Patos',
        "option_c": 'Porcos',
        "option_d": 'Pombos',
        "correct_choice": 'B',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual bicho amaldiçoa o Rigby e o transforma em uma espécie de lobisomen?',
        "option_a": 'Lobo',
        "option_b": 'Quati',
        "option_c": 'Gambá',
        "option_d": 'Pato',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Em qual esporte de mesa Benson jogava profissionalmente?',
        "option_a": 'Ping Pong',
        "option_b": 'Hockey de mesa',
        "option_c": 'Sinuca',
        "option_d": 'Pebolim',
        "correct_choice": 'B',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Mordecai e qual especie de passaro?',
        "option_a": 'Corvo',
        "option_b": 'Urraca-azul (blue jay)',
        "option_c": 'Falcao',
        "option_d": 'Canario',
        "correct_choice": 'B',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'O que Mordecai e Rigby querem assistir, mas são proíbidos pelo Benson, pois devem cuidar do Pairulito depois que ele machuca as costas?',
        "option_a": 'Luta livre',
        "option_b": 'Futebol americano',
        "option_c": 'Show do Soco no Ar',
        "option_d": 'Basquete',
        "correct_choice": 'A',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Antes de Apenas um Show: As Fitas Perdidas, quando foi ao ar o último episódio de Apenas um Show?',
        "option_a": '2015',
        "option_b": '2017',
        "option_c": '2019',
        "option_d": '2020',
        "correct_choice": 'B',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Em qual desses desenhos Musculoso e Fantasmão já apareceram?',
        "option_a": 'O Incrível Mundo de Gumball',
        "option_b": 'Titio Avô',
        "option_c": 'Steven Universo',
        "option_d": 'Jellystone',
        "correct_choice": 'B',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Em qual dessas habilidades inúteis o Mordecai é bom?',
        "option_a": 'Hamboning',
        "option_b": 'Pedra, Papel e Tesoura',
        "option_c": 'Ficar muito tempo sem piscar',
        "option_d": 'Body Building',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual o trabalho de Don, irmão do Rigby?',
        "option_a": 'Contador',
        "option_b": 'Chef',
        "option_c": 'Engenheiro',
        "option_d": 'Dublê',
        "correct_choice": 'A',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual é o único personagem do elenco principal que tem 5 dedos?',
        "option_a": 'Mordecai',
        "option_b": 'Saltitão',
        "option_c": 'Rigby',
        "option_d": 'Pairulito',
        "correct_choice": 'B',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'O que o pai da Margaret voa?',
        "option_a": 'uma vassoura',
        "option_b": 'um avião',
        "option_c": 'um balão',
        "option_d": 'um helicóptero',
        "correct_choice": 'D',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Os mestres do Mortal Kwon Do usam que tipo de corte de cabelo?',
        "option_a": 'Afro',
        "option_b": 'Moicano',
        "option_c": 'Mullet',
        "option_d": 'Careca',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual o veículo principal que Mordecai e Rigby usam durante a série?',
        "option_a": 'Carrinho de golfe',
        "option_b": 'Karts',
        "option_c": 'Motocas',
        "option_d": 'Skates',
        "correct_choice": 'A',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Em que jogo o Rigby sempre vence o Mordecai?',
        "option_a": 'Pedra, papel e tesoura',
        "option_b": 'Queda de braço',
        "option_c": 'Pega pega',
        "option_d": 'Quem pisca primeiro',
        "correct_choice": 'A',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Depois de terminar com a Margaret, quem o Mordecai namora?',
        "option_a": 'Eileen',
        "option_b": 'Starla',
        "option_c": 'Emily',
        "option_d": 'CJ',
        "correct_choice": 'D',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual matéria o Cavalo Festeiro precisa de ajuda de Mordecai e Rigby para passar?',
        "option_a": 'História Americana',
        "option_b": 'Matemática',
        "option_c": 'Biologia',
        "option_d": 'Espanhol',
        "correct_choice": 'A',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Quem ajuda o Mordecai quando ele tem um desentendimento com a CJ após uma confusão envolvendo a Margaret no Natal?',
        "option_a": 'Rigby',
        "option_b": 'Saxofonista Triste',
        "option_c": 'Saltitão',
        "option_d": 'Mordecai do Futuro',
        "correct_choice": 'B',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual era o prêmio ao completar o desafio Ovocelente?',
        "option_a": '1000 dólares',
        "option_b": 'uma coroa',
        "option_c": 'um boné',
        "option_d": 'um bolo',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual era a fraqueza do Martelo, chefão do jogo Ninguém Vence o Martelo?',
        "option_a": 'Salada',
        "option_b": 'Mobília',
        "option_c": 'Água',
        "option_d": 'Coisas azul',
        "correct_choice": 'B',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual é o trabalho do Mordecai e Rigby?',
        "option_a": 'Zeladores',
        "option_b": 'Manutenção',
        "option_c": 'Seguranças',
        "option_d": 'Gerentes do Parque',
        "correct_choice": 'A',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'O que acontece quando Mordecai e Rigby precisam trazer salsichas para o churrasco anual do parque?',
        "option_a": 'eles comem as salsichas',
        "option_b": 'as salsichas deixam eles ricos',
        "option_c": 'as salsichas atacam eles',
        "option_d": 'as salsichas congelam',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Em que episódio o Pairulito luta contra o Anti-Pairulito?',
        "option_a": 'Primeiro episódio da série',
        "option_b": 'Penúltimo episódio da série',
        "option_c": 'Último episódio da série',
        "option_d": 'Primeiro episódio da última temporada',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual animal é a esposa do Mordecai no final do show?',
        "option_a": 'Morcego',
        "option_b": 'Rato',
        "option_c": 'Pássaro',
        "option_d": 'Toupeira',
        "correct_choice": 'A',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Quem está casando no episódio Largada no Altar?',
        "option_a": 'Fantasmão e Célia',
        "option_b": 'Rigby e Eileen',
        "option_c": 'Musculoso e Starla',
        "option_d": 'Mordecai e Margaret',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Para que país o Benson vai para ensinar inglês?',
        "option_a": 'Japão',
        "option_b": 'China',
        "option_c": 'México',
        "option_d": 'África do Sul',
        "correct_choice": 'B',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Por que Mordecai e Rigby precisam lutar contra Klorgbane no lugar de Saltitão?',
        "option_a": 'Rigby machucou os dedos do Saltitão e ele não consegue lutar',
        "option_b": 'eles deixaram o Saltitão doente ao fazê-lo comer um mega burrito',
        "option_c": 'Saltitão ficou inconsciente depois que os dois o atropelaram sem querer',
        "option_d": 'Mordecai quer se exibir para a Margaret derrotando Klorgbane',
        "correct_choice": 'A',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual o nome do perfume que Mordecai usa e atrai unicórnios?',
        "option_a": 'Vez dos Caras',
        "option_b": 'Le Uni',
        "option_c": 'Cheiro no Ar',
        "option_d": 'Segura Essa',
        "correct_choice": 'A',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Quantos Contos de Terror do Parque tem?',
        "option_a": '5',
        "option_b": '6',
        "option_c": '7',
        "option_d": '8',
        "correct_choice": 'B',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Por que Mordecai escolhe jogar com Saltitão ao invés do Rigby no episódio Magos do Videogame?',
        "option_a": 'Porque o Rigby estava fedendo',
        "option_b": 'porque o Saltitão estava deprimido',
        "option_c": 'porque o Saltitão era melhor que o Rigby no jogo',
        "option_d": 'porque o Rigby estava sem conseguir enxergar',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual carro o Saltitão dirige?',
        "option_a": 'Ele não dirige',
        "option_b": 'um jipe',
        "option_c": 'um fusca',
        "option_d": 'uma kombi',
        "correct_choice": 'D',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Por que Mordecai, Rigby, Eileen e Margaret invadem um zoológico à noite?',
        "option_a": 'para tirar foto com um urso assassino',
        "option_b": 'para resgatar o porco do Benson',
        "option_c": 'para ganhar uma aposta feita por Musculoso',
        "option_d": 'para recuperar o celular roubado da Margaret',
        "correct_choice": 'A',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual o nome do show policial favorito do Mordecai e do Rigby?',
        "option_a": 'Casos de Polícia',
        "option_b": 'Arquivo Frio',
        "option_c": 'Carter & Briggs',
        "option_d": 'Duster & Madison',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Mordecai e Rigby jogam basquete contra Musculoso e Fantasmão valendo o que?',
        "option_a": 'um sanduíche',
        "option_b": 'tempo no computador',
        "option_c": 'fazer as tarefas da outra dupla por uma semana',
        "option_d": 'Pintar o cabelo do perdedor de loiro',
        "correct_choice": 'B',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual celebridade aparece como ele mesmo no show?',
        "option_a": 'Tyler, The Creator',
        "option_b": 'Donald Glover',
        "option_c": 'Mark Hammil',
        "option_d": 'Neil deGrasse Tyson',
        "correct_choice": 'D',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual desses atores famosos já fez mais de um personagem em Apenas um Show?',
        "option_a": 'Tim Curry',
        "option_b": 'Courteney Cox',
        "option_c": 'Terry Crews',
        "option_d": 'Donald Glover',
        "correct_choice": 'A',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Por que o Pairulito bebe um galão inteiro de leite de uma vez só?',
        "option_a": 'para ficar com ossos fortes',
        "option_b": 'Para fazer PairuShakes',
        "option_c": 'para poder participar da Noite da Rapaziada',
        "option_d": 'para vencer um desafio proposto pelo Benson',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Por que Rigby aprende a pular de paraquedas?',
        "option_a": 'para chegar em grande estilo no trabalho',
        "option_b": 'para vencer uma aposta',
        "option_c": 'para realizar uma promessa feita na época do colegial',
        "option_d": 'para impressionar a Eileen',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual o nome do pai do Rigby?',
        "option_a": 'Sherm',
        "option_b": 'Carlos',
        "option_c": 'Ricky',
        "option_d": 'Josh',
        "correct_choice": 'A',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'A qual filme o episódio Fim de Semana no Benson faz referência?',
        "option_a": 'Vivendo a Vida Adoidado',
        "option_b": 'Superbad',
        "option_c": 'Esqueceram de Mim',
        "option_d": 'Um Morto Muito Louco',
        "correct_choice": 'D',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Em que temporada temos o primeiro episódio especial de Halloween, Contos de Terror do Parque?',
        "option_a": '1',
        "option_b": '2',
        "option_c": '3',
        "option_d": '4',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Quantas vezes o Rigby já morreu na série?',
        "option_a": '0',
        "option_b": '1',
        "option_c": '2',
        "option_d": '3',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual desses personagens não vai para o espaço na última temporada?',
        "option_a": 'Margaret',
        "option_b": 'Eileen',
        "option_c": 'Saltitão',
        "option_d": 'Musculoso',
        "correct_choice": 'A',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Pelo que o Musculoso quase abandona o parque?',
        "option_a": 'ser piloto da Nascar',
        "option_b": 'ser locutor de rádio',
        "option_c": 'ser modelo de pança',
        "option_d": 'ser palhaço de rodeio',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Complete a frase: BOLO DE…',
        "option_a": 'BAUNILHA',
        "option_b": 'ANIVERSÁRIO',
        "option_c": 'GRAÇA',
        "option_d": 'CHOCOLATE',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'De que artista o personagem Gary é uma paródia?',
        "option_a": 'Freddy Mercury',
        "option_b": 'David Bowie',
        "option_c": 'Michael Jackson',
        "option_d": 'Eddie Murphy',
        "correct_choice": 'B',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual música famosa dos anos 80 Mordecai e Rigby cantam no karaokê no episódio Vídeo de Karaokê?',
        "option_a": 'We’re not gonna take it do Twisted Sisters',
        "option_b": 'We are the champions do Queen',
        "option_c": 'Starman do David Bowie',
        "option_d": 'Thriller do Michael Jackson',
        "correct_choice": 'A',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual música famosa dos anos 80 Pairulito canta no karaokê no episódio Vídeo de Karaokê?',
        "option_a": 'We’re not gonna take it do Twisted Sisters',
        "option_b": 'We are the champions do Queen',
        "option_c": 'Starman do David Bowie',
        "option_d": 'Footloose de Kenny Loggins',
        "correct_choice": 'D',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Do que o Mordecai se envergonha de ter participado na época do colegial?',
        "option_a": 'Líderes de torcida',
        "option_b": 'Clube de Matemática',
        "option_c": 'Banda marcial',
        "option_d": 'Grupo de Teatro',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Quem foi a única pessoa a completar o desafio Ovocelente e sobreviver?',
        "option_a": 'Rigby',
        "option_b": 'Mordecai',
        "option_c": 'Benson',
        "option_d": 'Musculoso',
        "correct_choice": 'B',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual dessas fobias o Rigby tem?',
        "option_a": 'Claustrofobia',
        "option_b": 'Aracnofobia',
        "option_c": 'Acrofobia',
        "option_d": 'Agorafobia',
        "correct_choice": 'A',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Quantas filhas Rigby e Eileen tem no final da série?',
        "option_a": '0',
        "option_b": '1',
        "option_c": '2',
        "option_d": '3',
        "correct_choice": 'C',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Onde o Rigby dorme?',
        "option_a": 'Em uma cama',
        "option_b": 'Em um trampolim',
        "option_c": 'Em uma pilha de roupas',
        "option_d": 'No chão',
        "correct_choice": 'B',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual desses personagens admitiu que odeia tomar banho?',
        "option_a": 'Mordecai',
        "option_b": 'Fantasmão',
        "option_c": 'Saltitão',
        "option_d": 'Rigby',
        "correct_choice": 'D',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'De qual animal Benson já demonstrou ser muito fã, tendo até mesmo quadros desse bicho no seu apartamento?',
        "option_a": 'Gatos',
        "option_b": 'Cachorros',
        "option_c": 'Pássaros',
        "option_d": 'Guaxinins',
        "correct_choice": 'A',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Tirando Mordecai e Rigby, qual o personagem que mais apareceu na série durante suas 8 temporadas?',
        "option_a": 'Musculoso',
        "option_b": 'Benson',
        "option_c": 'Fantasmão',
        "option_d": 'Saltitão',
        "correct_choice": 'B',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual o único funcionário do parque que não mora no parque?',
        "option_a": 'Saltitão',
        "option_b": 'Musculoso',
        "option_c": 'Fantasmão',
        "option_d": 'Benson',
        "correct_choice": 'D',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual desses personagens já foi hippie no passado?',
        "option_a": 'Musculoso',
        "option_b": 'Saltitão',
        "option_c": 'Pairulito',
        "option_d": 'Benson',
        "correct_choice": 'D',
        "category": 'Apenas um Show',
    },
    {
        "prompt": 'Qual desses personagens adora fazer pegadinhas com Mordecai e Rigby?',
        "option_a": 'Musculoso',
        "option_b": 'Benson',
        "option_c": 'Pairulito',
        "option_d": 'Saltitão',
        "correct_choice": 'A',
        "category": 'Apenas um Show',
    },
]
